### ISSUE TITLE
Some random thoughts, may not have any value :)

### ISSUE THREAD

**Issue by VikParuchuri** [kazuar/country_data_codes#1]
Saw the post -- good stuff!  Have some comments that may or may not be useful:
- Why not skip scraping the country code page urls?  (like https://en.wikipedia.org/wiki/Country_codes:_A).  Instead, you could just iterate from A to Z, construct the url, and if it 404s, then skip, otherwise scrape.  Saves some code. (for example https://en.wikipedia.org/wiki/Country_codes:_J redirects to https://en.wikipedia.org/wiki/Country_codes:_J-K, so it's not a problem that some of the urls aren't regular)
- Why make `alpha_two_to_country_name` and `alpha_three_to_country_name`?  There won't be any collisions, because length is different, so you could store everything in one dictionary.
- Why not just json serialize a dict in the format you want to use for lookup?  Then you don't need this: `country_data["country_name"].lower(): country_data for country_data in self._countries_data` every time you load.

Anyways, feel free to close/delete if you want, just had some questions :)

**Comment by kazuar** [comment]
Hi Vik!
Thanks for taking the time to go over the code.

1) Why not skip scraping the country code page urls? - That's a good idea, I actually hadn't considered that. However, when I run scraping tasks I usually want to make sure that I don't miss anything. That's why I prefer holding the actual list of urls instead of "guessing" what the next url should be (I'd like to be organized about what I'm scraping). In this example, you won't get a 404, you will still get the same wikipedia page for all the letters in the range. For example, "J" and "K" will give you the same Wikipedia page which will result in redundant requests.

2) Why make alpha_two_to_country_name and alpha_three_to_country_name? - I've actually debated with myself if I should use two dicts or one (as you suggested) - in the end I decided on two because I believe that every object should have it's own use case. Of course, this is debatable :)

3) Why not just json serialize a dict in the format you want to use for lookup? - I Usually like to keep my scraping and "business logic" in two separate steps. So I would prefer to save my scraped data "as is" and format it for my specific use case after I load it. If this was a bigger use case, I would probably also save the raw HTML that I initially scraped as well. In my mind, once you scraped the data (step 1) you can do whatever you want with it ("business logic 1") and they should be separated because you might also want to format it in a different way in some other use case ("business logic 2").

Hope this answered your questions :)
